name: chat_app_ui
description: UI for a chat app made using Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Cupertino Icons
  cupertino_icons: ^0.1.3
  # Stacked
  stacked: ^1.7.6
  # third-party services
  stacked_services: ^0.5.2
  # navigation
  auto_route: ^0.6.7
  # inversion of control
  get_it: ^4.0.4
  injectable: ^1.0.4
  # loading animations
  flutter_spinkit: ^4.1.2+1
  # logger
  logger: ^0.9.2

  # Font Awesome Flutter
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^1.10.1
  auto_route_generator: ^0.6.8
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
